### ISSUE TITLE
fix: in the workshop, pipeline name for the resource configure does not match the later example output

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/kratix-docs#145]
## Context

In workshop part ii, write your own promise: https://docs.kratix.io/workshop/part-ii/writing-your-first-promise#workflow

We ask people run a command `kratix add container resource/configure/mypipeline --image kratix-workshop/app-pipeline-image:v1.0.0`

This will write out a resource configure with pipeline name `mypipeline`. However, later in the same section, the resource configure workflow example we have is:
```
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: resource-configure
          spec:
            containers:
              - name: create-resources # not correct
                image: kratix-workshop/app-pipeline-image:v1.0.0
                command: [ resource-configure ]
                ```
There's inconsistency on this through out the workshop. Some refers to `resource-configure` pipeline (like the job name output example), some refers to `mypipeline`.
